# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024d10a08f1313c480efd1d7985c4ca38e6fb8fa98dc3b971f79babd6b1bf2eda873d97386a32b725f79ebad0d8c3613e4a4da6fdc7e3f8ad08fdcfc3219e652

test:
  secret_key_base: 740e4db4b931ff35d7b0d79a01a972149c83f0334a6236008c5249eec7c3440b2a57301fe9c6280b32a0ae2c42d451d54313a8c47d4e2bc17cbc7332c8239cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
